### PR TITLE
Add public S3 buckets to mozilla-iam AWS account

### PR DESCRIPTION
**Pull request by gene1wood**
@The-smooth-operator , could you review this?

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
Hi @gene1wood this looks good. I'm not enough familiar with CloudFormation to find issues there but all seems legit.
I appreciate you added notes (for example explaining the buckets replication).
It could be awesome if you can drop a note, in the code, using a bucket tag, or here in the PR explaining why we need these buckets

**Comment by gene1wood** [comment]
Sure! These are generic/common public buckets that can be used to host any public data in the mozilla-iam account. I would have used the existing public bucket that @andrewkrug made but it's in the wrong region. These new buckets have the region in the name and there's one for us-east-1 and us-west-2.

My use case for these common buckets is that I have [AWS Lambda python code](https://github.com/mozilla-iam/federated-aws-rp/tree/master/functions/federated_aws_rp) which needs to be hosted in an S3 bucket to be accessed by CloudFormation. With these buckets I'll be able to deploy the AWS Federated relying party which can be accessed at https://aws.sso.mozilla.com/ and will allow mozillians to log into their AWS accounts.

**Comment by The-smooth-operator** [comment]
thanks for the explanation. I'm looking forward to use the aws sso tool!!

**Comment by gene1wood** [comment]
@The-smooth-operator Cool! Are you able to review or merge this?

**Comment by The-smooth-operator** [comment]
sure, looks good. Merging it

**Pull request merged**
