### PR TITLE
Stand up SSO/Auth0 proxy in front of Graylog

### PR DESCRIPTION
**Pull request by ziegeer**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
@ziegeer looks good, thanks!
Could you please add the Dockerfile for the OIDC proxy to this repo?

**Comment by ziegeer** [comment]
Added, is that a good location for them in the repo?

**Comment by The-smooth-operator** [comment]
@ziegeer actually better to add it to the dockerfiles folder in the root of the repo. Thanks!

**Comment by The-smooth-operator** [comment]
lovely!

**Pull request merged**
